#!/bin/sh
#
# Custom script for managing mongodb.
# This abstracts away starting/stopping the multiple mongod instances
# we require.
#

start() {
    echo "Starting mongodb on default port with dbpath $HOME/kadata/mongo"
    # Note - default mongo port 27017
    /usr/bin/mongod --fork \
        --dbpath "$HOME/kadata/mongo" \
        --logpath "$HOME/log/mongo/mongo.log"
    echo "Starting mongodb on port 12345 with dbpath $HOME/kadata2/mongo"
    /usr/bin/mongod --fork \
        --directoryperdb \
        --port 12345 \
        --dbpath "$HOME/kadata2/mongo" \
        --logpath "$HOME/log/mongo/mongo2.log"
}
stop() {
    echo "Killing all mongod processes owned by $USER"

    # Will error if none are found, but that's OK.
    killall mongod 2> /dev/null
}
restart() {
  stop
  start
}
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    echo "Does not apply"
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    restart
    ;;
  reload)
    restart
    ;;
  force-reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
    exit 2
esac

exit $?
