# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "hashicorp/precise64"

    # Solr will be available at localhost:9001 on the host machine after this
    config.vm.network "forwarded_port", guest: 80, host: 9001

    # These are run sequentially. We use the install script in the repo so that
    # we stay consistent with the production server, and just do some steps
    # before and after to make it (a) work in development and (b) run without
    # human interaction.
    config.vm.provision "shell", path: "vagrant_data/preinstall.sh"
    config.vm.provision "shell", path: "scripts/install_solr.bash"
    config.vm.provision "shell", path: "vagrant_data/postinstall.sh"
end
